import test from 'node:test';import assert from 'node:assert/strict';
import{mkdtempSync,writeFileSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{spawnSync,spawn}from'node:child_process';
const script=new URL('./mvp-registry.mjs',import.meta.url).pathname;
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'mvp-registry-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const registry=join(dir,'registry.json');let n=0;
 function call(command,options={},expected=0){const args=[script,command,'--registry',registry,...Object.entries(options).flatMap(([k,v])=>['--'+k,String(v)])];const result=spawnSync(process.execPath,args,{encoding:'utf8'});assert.equal(result.status,expected,result.stderr);return result.stdout?JSON.parse(result.stdout):result;}
 function candidate(slug='fixture-tool',key='agency redirect map review',ids=[]){const path=join(dir,'candidate-'+n+++'.json');writeFileSync(path,JSON.stringify({name:'Fixture tool',slug,task_key:key,buyer:'Agency owner',trigger:'Migration map ready',inputs:['Synthetic CSV'],accepted_output:'Reviewed mapping CSV',purchase_reason:'One migration project',novelty_review:{decision:'distinct',compared_entry_ids:ids,rationale:'Different buyer task from prior entries'}}));return path;}
 return{dir,registry,call,candidate};}
test('runs get fresh identities/seeds and rotate least-used discovery families',t=>{const f=fixture(t),a=f.call('start').run,b=f.call('start').run;assert.notEqual(a.id,b.id);assert.notEqual(a.seed,b.seed);assert.equal(a.families.length,4);assert.equal(new Set(a.families).size,4);assert(!a.families.some(x=>b.families.includes(x)));});
test('normalized task duplicates restart even with a different product slug',t=>{const f=fixture(t),a=f.call('start').run,b=f.call('start').run;const first=f.call('reserve',{'run-id':a.id,candidate:f.candidate()});const result=f.call('reserve',{'run-id':b.id,candidate:f.candidate('renamed-tool','Agency -- Redirect MAP review')},2);assert.equal(result.restart,true);assert.equal(result.match.id,first.entry.id);assert.equal(f.call('list').entries.length,1);});
test('stale semantic review fails closed; refreshed review can reserve a distinct task',t=>{const f=fixture(t),a=f.call('start').run,b=f.call('start').run;const first=f.call('reserve',{'run-id':a.id,candidate:f.candidate()});f.call('reserve',{'run-id':b.id,candidate:f.candidate('different-tool','teacher assignment reconciliation')},1);const next=f.call('reserve',{'run-id':b.id,candidate:f.candidate('different-tool','teacher assignment reconciliation',[first.entry.id])});assert.equal(next.outcome,'reserved');});
test('owner controls reservation and implemented products cannot be released',t=>{const f=fixture(t),a=f.call('start').run,b=f.call('start').run;const entry=f.call('reserve',{'run-id':a.id,candidate:f.candidate()}).entry;f.call('release',{'run-id':b.id,id:entry.id,reason:'Wrong owner'},1);f.call('mark',{'run-id':a.id,id:entry.id,'release-status':'release-blocked',repository:'https://github.com/Nex2i/fixture','app-url':'https://fixture.nex2i.com'});f.call('release',{'run-id':a.id,id:entry.id,reason:'Cannot erase built product'},1);assert.equal(f.call('list').entries[0].release_status,'release-blocked');});
test('semantic overlap rejection is logged without reserving or provisioning',t=>{const f=fixture(t),a=f.call('start').run,b=f.call('start').run;const entry=f.call('reserve',{'run-id':a.id,candidate:f.candidate()}).entry;const rejected=f.call('reject',{'run-id':b.id,'match-id':entry.id,'candidate-name':'Renamed map checker',reason:'Same buyer input and output'},2);assert.equal(rejected.restart,true);assert.equal(f.call('list').runs[1].rejected_duplicates.length,1);assert.equal(f.call('list').entries.length,1);});
test('simultaneous duplicate reservations yield only one winner',async t=>{const f=fixture(t),a=f.call('start').run,b=f.call('start').run;
 function launch(run,slug){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[script,'reserve','--registry',f.registry,'--run-id',run.id,'--candidate',f.candidate(slug)]);let out='',err='';child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);child.on('error',reject);child.on('close',code=>resolve({code,out,err}));});}
 const results=await Promise.all([launch(a,'parallel-a'),launch(b,'parallel-b')]);assert.deepEqual(results.map(r=>r.code).sort(),[0,2]);assert.equal(f.call('list').entries.length,1);});
test('corrupt registries are preserved and never silently reset',t=>{const f=fixture(t);writeFileSync(f.registry,'broken registry');f.call('start',{},1);assert.equal(readFileSync(f.registry,'utf8'),'broken registry');});

test('an abandoned reservation cannot later resurrect a duplicate implementation',t=>{const f=fixture(t),run=f.call('start').run;const entry=f.call('reserve',{'run-id':run.id,candidate:f.candidate()}).entry;f.call('release',{'run-id':run.id,id:entry.id,reason:'Abandoned before implementation'});f.call('mark',{'run-id':run.id,id:entry.id,'release-status':'customer-ready',repository:'https://github.com/Nex2i/fixture','app-url':'https://fixture.nex2i.com'},1);assert.equal(f.call('list').entries[0].status,'abandoned');});

test('portfolio publication is owner-bound, post-implementation and idempotent',t=>{const f=fixture(t),run=f.call('start').run;const entry=f.call('reserve',{'run-id':run.id,candidate:f.candidate()}).entry;const args={'run-id':run.id,id:entry.id,url:'https://portfolio.example.com/','source-revision':'verified-commit','deployment-id':'deploy-1','verification-reference':'docs/verification.md#portfolio'};f.call('portfolio',args,1);f.call('mark',{'run-id':run.id,id:entry.id,'release-status':'release-blocked',repository:'https://github.com/Nex2i/fixture','app-url':'https://fixture.nex2i.com'});f.call('portfolio',{...args,'run-id':'wrong-owner'},1);f.call('portfolio',{...args,url:'http://portfolio.example.com/'},1);const a=f.call('portfolio',args),b=f.call('portfolio',{...args,'deployment-id':'deploy-2'});assert.equal(a.entry.portfolio.entry_key,entry.id);assert.equal(b.entry.portfolio.deployment_id,'deploy-2');assert.equal(f.call('list').entries.length,1);});
